[build]
target = ["x86_64-pc-windows-gnu", "x86_64-unknown-linux-gnu"] # , "x86_64-apple-darwin", "aarch64-apple-darwin"

# [target.x86_64-pc-windows-gnu]
# linker = "x86_64-w64-mingw32-ld"
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]
