name: Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Add targets and mingw64
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64
        rustup target add x86_64-pc-windows-gnu
    - name: Run checks
      run: cargo check --verbose
